version: 0.0
os: linux
files:
  - source: .
    destination: /usr/local/codedeployresources
  - source: ./scripts/xfire-fab-analyser.service
    destination: /etc/systemd/system/
permissions:
  - object: [/usr/local/codedeployresources/aws/scripts/,/usr/local/codedeployresources/xfire-fabrication-process-analyzer]
    owner: root
    mode: 755
    type:
      - file
      - directory
hooks:
  ApplicationStop:
    - location: aws/scripts/application-stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: aws/scripts/validate-service.sh
      timeout: 300
      runas: root
